version: '3.8'
services:
  server:
    container_name: server
    image: server
    ports:
      - 3333:3333
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
      - DATABASE_HOST=mariadb
    healthcheck:
      test: wget localhost:3333/api/health -q -O - > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy
  swagger-ui:
    container_name: swagger
    image: "swaggerapi/swagger-ui:v3.25.0"
    ports:
      - "8080:8080"
    volumes:
      - ./${SWAGGER_JSON_FILE}:/usr/share/spec/${SWAGGER_JSON_FILE}
    environment:
      SWAGGER_JSON: /usr/share/spec/${SWAGGER_JSON_FILE}
    healthcheck:
      test: ["CMD", "wget", "localhost:8080 -q -O - > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5