services:
  server:
    restart: always
    container_name: et-server
    image: et-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 4004:4000
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    networks:
      - expense-tracker-api_default

networks:
  expense-tracker-api_default:
    external: true
