export const sampleExpenses = [
  {
    id: '1',
    name: 'coffee',
    description: 'Coffee',
    amount: 2.0,
    account: 'Debit Card',
    category: 'Food',
    completed: true,
  },
  {
    id: '2',
    name: 'lunch',
    description: 'Lunch',
    amount: 10.0,
    account: 'Cash',
    category: 'Food',
    completed: false,
  },
  {
    id: '3',
    name: 'beer',
    description: 'Hazy IPA',
    amount: 3.5,
    account: 'Credit Card',
    category: 'Beverages',
    completed: true,
  },
  {
    id: '4',
    name: 'cake',
    description: 'Kinder Bueno',
    amount: 2.25,
    account: 'Żappsy',
    category: 'Snacks',
    completed: true,
  },
  {
    id: '5',
    name: 'dinner',
    description: 'Dinner',
    amount: 15.0,
    account: 'Cash',
    category: 'Food',
    completed: false,
  },
  {
    id: '6',
    name: 'tea',
    description: 'Tea',
    amount: 1.5,
    account: 'Cash',
    category: 'Beverages',
    completed: true,
  },
  {
    id: '7',
    name: 'breakfast',
    description: 'Breakfast',
    amount: 5.0,
    account: 'Debit Card',
    category: 'Food',
    completed: false,
  },
  {
    id: '8',
    name: 'soda',
    description: 'Coca-Cola',
    amount: 1.0,
    account: 'Credit Card',
    category: 'Beverages',
    completed: true,
  },
  {
    id: '9',
    name: 'croissant',
    description: 'Croissant',
    amount: 1.5,
    account: 'Żappsy',
    category: 'Snacks',
    completed: true,
  },
  {
    id: '10',
    name: 'dinner',
    description: 'Dinner',
    amount: 20.0,
    account: 'Cash',
    category: 'Food',
    completed: false,
  },
];
